### ISSUE TITLE
Almost all of the tests are failing

### ISSUE THREAD

**Issue by Samsinite** [charge-io/chargeio-gem#1]
Cloned the repo, tried to run the tests, and almost all of them are failing:
```sh
Finished in 1.12 seconds (files took 2.16 seconds to load)
215 examples, 207 failures
```

Recommend switching to `pry-byebug` instead of `ruby-debug` or even `ruby-debug19` as they will not run on `ruby 2.x`. 

Also recommend moving `net-http-spy` as  development dependencies into the gemspec, and removing `money` from the Gemfile as it will be pulled in through the gemspec.

**Comment by Samsinite** [comment]
FYI, running these on Ruby 2.3.1

**Comment by Samsinite** [comment]
You can see our dependency updates to get the tests running (not passing) on Ruby 2.3.1 at https://github.com/wildland/chargeio-gem

**Comment by udev** [comment]
@Samsinite thank you for the feedback. We are presently working to bring this project current. Please stay tuned.

**Comment by udev** [comment]
Looks like a couple of stealth updates were rolled out to address this issue. We're working on improving the process in the future but I'll close this issue out for now. Please create a new issue or reopen if you are still running in to any issues.

0b8ccf7fefda37f9a171baae78b5ae6ae2393b82
e3231acd4412be17c5a3bee34cf631c1828a777a
